# 📚 **NumPy, Pandas, Matplotlib, and Seaborn Practice Questions**
---
This notebook contains four sets of practice questions covering NumPy, Pandas, Matplotlib, and Seaborn. Complete the tasks below and run the respective cells.

## 🧠 **Question 1: NumPy Array Manipulation**
1. Create a 1D NumPy array with integers from **1 to 24**.  
2. Reshape the array into a **4x6 matrix**.  
3. Extract the **third row** and **second column** from the reshaped array.  
4. Transpose the matrix and display the result.

In [2]:
# Solution for Question 1
import numpy as np
arr=np.arange(1, 25)
print(arr)
matrix=arr.reshape(4, 6)
print("4x6 matrix:\n",matrix)
third_row=matrix[2]
print("third_row:\n",third_row)
second_column=matrix[:, 1]
print("second_column:\n",second_column)
transposed_matrix=matrix.T
print("Transposed Matrix:\n", transposed_matrix)




# Your code here

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
4x6 matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
third_row:
 [13 14 15 16 17 18]
second_column:
 [ 2  8 14 20]
Transposed Matrix:
 [[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]


## 🧠 **Question 2: Array Element Extraction**
1. Create a **5x5 NumPy array** with random integers between **10 and 100**.  
2. Extract all the **even numbers** from the array.  
3. Replace all numbers **greater than 50** with **0**.  
4. Extract the diagonal elements of the array.

In [3]:
# Solution for Question 2
import numpy as np
np.random.seed(42)
random_matrix = np.random.randint(10, 100, (5, 5))
print("5x5 Matrix:\n", random_matrix)
even_numbers = random_matrix[random_matrix % 2 == 0]
print("\nEven Numbers:\n", even_numbers)
modified_matrix = random_matrix.copy()
modified_matrix[modified_matrix > 50] = 0
print("\nModified Matrix (Numbers > 50 replaced with 0):\n", modified_matrix)
diagonal_elements = np.diag(modified_matrix)
print("\nDiagonal Elements:\n", diagonal_elements)

# Your code here

5x5 Matrix:
 [[61 24 81 70 30]
 [92 96 84 84 97]
 [33 12 31 62 11]
 [97 39 47 11 73]
 [69 30 42 85 67]]

Even Numbers:
 [24 70 30 92 96 84 84 12 62 30 42]

Modified Matrix (Numbers > 50 replaced with 0):
 [[ 0 24  0  0 30]
 [ 0  0  0  0  0]
 [33 12 31  0 11]
 [ 0 39 47 11  0]
 [ 0 30 42  0  0]]

Diagonal Elements:
 [ 0  0 31 11  0]


## 🧠 **Question 3: DataFrame Creation and Operations (Pandas)**
1. Create a Pandas DataFrame containing the following data:

| Student_ID | Name   | Subject | Marks |
|------------|--------|---------|-------|
| 1          | Alice  | Math    | 88    |
| 2          | Bob    | Science | 75    |
| 3          | Carol  | History | 92    |
| 4          | David  | Math    | 85    |
| 5          | Eva    | Science | 90    |

2. Find the **average marks** for each subject.  
3. Add a new column named **Grade** based on the marks:
- Marks ≥ 90 → A
- Marks ≥ 80 → B
- Marks ≥ 70 → C
- Else → D

In [ ]:
# Solution for Question 3
import pandas as pd
data = {
    'Student_ID': [1, 2, 3, 4, 5],
    'Name': ['Alice', 'Bob', 'Carol', 'David', 'Eva'],
    'Subject': ['Math', 'Science', 'History', 'Math', 'Science'],
    'Marks': [88, 75, 92, 85, 90]
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)
avg_marks = df.groupby('Subject')['Marks'].mean()
print("\nAverage Marks for Each Subject:\n", avg_marks)
def assign_grade(marks):
    if marks >= 90:
        return 'A'
    elif marks >= 80:
        return 'B'
    elif marks >= 70:
        return 'C'
    else:
        return 'D'

df['Grade'] = df['Marks'].apply(assign_grade)
print("\nDataFrame with Grades:\n", df)

# Your code here

DataFrame:
    Student_ID   Name  Subject  Marks
0           1  Alice     Math     88
1           2    Bob  Science     75
2           3  Carol  History     92
3           4  David     Math     85
4           5    Eva  Science     90

Average Marks for Each Subject:
 Subject
History    92.0
Math       86.5
Science    82.5
Name: Marks, dtype: float64

DataFrame with Grades:
    Student_ID   Name  Subject  Marks Grade
0           1  Alice     Math     88     B
1           2    Bob  Science     75     C
2           3  Carol  History     92     A
3           4  David     Math     85     B
4           5    Eva  Science     90     A


## 🧠 **Question 4: Dataset Analysis (Pandas, Matplotlib, Seaborn)**
Use the dataset `diabetes.csv` and perform the following tasks:

1. Display the **BMI** and **Blood Pressure** for samples with **index ranging from 20 to 40**.  
2. Find how many patients have **BMI > 30**.  
3. Find the **mean and standard deviation** of the **Glucose** levels.  
4. Plot a **boxplot** for the column **Insulin**.  
5. Create a **heatmap** showing the correlation between the numerical columns in the dataset.

In [6]:
# Solution for Question 4
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('diabetes.csv')
bmi_bp_subset = df.loc[20:40, ['BMI', 'BloodPressure']]
print("BMI and Blood Pressure for index 20 to 40:\n", bmi_bp_subset)
bmi_above_30_count = (df['BMI'] > 30).sum()
print("\nNumber of patients with BMI > 30:", bmi_above_30_count)
glucose_mean = df['Glucose'].mean()
glucose_std = df['Glucose'].std()
print("\nGlucose Levels - Mean:", glucose_mean, "| Standard Deviation:", glucose_std)
plt.figure(figsize=(6, 4))
sns.boxplot(x=df['Insulin'])
plt.title("Boxplot of Insulin Levels")
plt.xlabel("Insulin")
plt.show()

# Your code here

FileNotFoundError: [Errno 2] No such file or directory: 'diabetes.csv'